version: '3'
services:

  mailhog:
    image: mailhog/mailhog
    networks:
      - test_network

  postgres:
    image: postgres:9.5
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=poc_features
    networks:
      - test_network

  redis:
    image: redis
    networks:
      - test_network

  app:
    image: registry.heroku.com/peaceful-refuge-95132/web
    environment:
      - RAILS_LOG_TO_STDOUT=true
      - RAILS_ENV=features
      - MAILHOG_HOST=mailhog
      - RAILS_MASTER_KEY
      - GITHUB_CLIENT_ID
      - GITHUB_SECRET
      - DATABASE_HOST=postgres
      - REDIS_URL=redis://redis:6379
    depends_on:
      - postgres
      - redis
      - mailhog
    networks:
      test_network:
        aliases:
          - app.com
          - www.app.com
          - bootcamp.app.com
          - dashboard.app.com
    command: >
      /bin/bash -c "
        while ! nc -z postgres 5432;
        do
          echo Waiting for PG;
          sleep 1;
        done;
        rake db:schema:load;
        rm -f /app/tmp/pids/server.pid;
        foreman start;
      "

  features:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
        - app
    environment:
      - CUCUMBER_HOST=http://www.app.com:3000
      - POSTGRES_HOST=postgres
      - GITHUB_TEST_EMAIL
      - GITHUB_TEST_PASSWORD
      - GITHUB_NON_PUBLIC_EMAIL
      - GITHUB_NON_PUBLIC_PASSWORD
    networks:
      - test_network
    command: >
      /bin/bash -c "
        while ! nc -z www.app.com 3000;
        do
          echo Waiting for app;
          sleep 1;
        done;
        cucumber;
        cat /app/chromedriver.log;
      "

networks:
  test_network:
    driver: bridge
